application: paste-math
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: static/favicon\.ico


- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /new
  script: main.py
  login: admin

- url: /edit/.*
  script: main.py
  login: admin

- url: /admin
  script: main.py
  login: admin

- url: .*
  script: main.py

libraries:
- name: webapp2
  version: "2.5.1"
