application: paste-math
version: 2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /icon\.ico
  static_files: static/icon.ico
  upload: static/icon\.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /new
  script: main.py
  login: admin

- url: /edit/.*
  script: main.py
  login: admin

- url: .*
  script: main.py

libraries:
- name: webapp2
  version: "2.5.1"
